### ISSUE TITLE
Installation failure (unsupported kernel)

### ISSUE THREAD

**Issue by MadissonG** [ahkehra/high_perf_dac#13]
A few months back I installed v5.5 successfully on Evolution X on k20pro. While I tried to upgrade today I got this error, although Ver 5.5 still installing properly and working. Kernel being:4.14.327-SOVIET-STAR-//bfed7dee9a.

**Comment by MadissonG** [comment]
Magisk log:

- Copying zip to temp directory
- Installing high_perf_dac-v6.zip
- Device is system-as-root
Archive:  /data/user/0/oqn.sudj.txbm.hfvn/cache/flash/install.zip
  inflating: module.prop
****************
 High perf DAC 
 by reallyakera 
****************
Archive:  /data/user/0/oqn.sudj.txbm.hfvn/cache/flash/install.zip
  inflating: customize.sh
*******************
 Powered by Magisk 
*******************
Archive:  /data/user/0/oqn.sudj.txbm.hfvn/cache/flash/install.zip
  inflating: LICENSE
  inflating: README.md
  inflating: customize.sh
  inflating: module.prop
  inflating: service.sh
- Extracting module files
- Done
+ print
+ ui_print 
+ true
+ echo 
+ ui_print '• Device : Mi 9T Pro'
+ true
+ echo '• Device : Mi 9T Pro'
+ ui_print '• Android : 13'
+ true
+ echo '• Android : 13'
+ ui_print '• Hardware : qcom'
+ true
+ echo '• Hardware : qcom'
+ ui_print 
+ true
+ echo 
+ extract
+ ui_print '- Extracting module files'
+ true
+ echo '- Extracting module files'
+ unzip -o /data/user/0/oqn.sudj.txbm.hfvn/cache/flash/install.zip module.prop -d /data/adb/modules_update/high_perf_dac

• Device : Mi 9T Pro
• Android : 13
• Hardware : qcom

- Extracting module files
Archive:  /data/user/0/oqn.sudj.txbm.hfvn/cache/flash/install.zip
  inflating: module.prop
+ unzip -o /data/user/0/oqn.sudj.txbm.hfvn/cache/flash/install.zip service.sh -d /data/adb/modules_update/high_perf_dac
Archive:  /data/user/0/oqn.sudj.txbm.hfvn/cache/flash/install.zip
  inflating: service.sh
+ ui_print '• Codename : '
+ true
+ echo '• Codename : '
+ detect
+ '[' qcom '==' qcom ]
+ ui_print 
+ true
+ echo 
+ ui_print '• ✓ Qcom Detected'
+ true
+ echo '• ✓ Qcom Detected'
+ ui_print 
+ true
+ echo 
+ '[' 
sh: missing ]
+ ui_print 
+ true
+ echo 
+ ui_print '- ! Failed because your Kernel is Not Supported'
+ true
+ echo '- ! Failed because your Kernel is Not Supported'
+ ui_print 
+ true
+ echo 
+ abort
+ ui_print 
+ true
+ echo 
+ true
+ '[' '!' -z /data/adb/modules_update/high_perf_dac ]
+ rm -rf /data/adb/modules_update/high_perf_dac
+ rm -rf /dev/tmp
+ exit 1
• Codename : 

• ✓ Qcom Detected


- ! Failed because your Kernel is Not Supported


! Installation failed

**Comment by theduffster** [comment]
The new version added code to test whether the user's kernel is supported. Unfortunately getting this error means your kernel is not supported and this modification was almost certainly never working in the first place. 

Same thing happened to me, sorry.

See the other discussions under Issues for more information.

**Comment by MadissonG** [comment]
Well, with the version 5.5 I can clearly hear it works. Sound becomes quite louder and there's much more details when listening on Tidal HiFi quality. I switched the module on and off (needed system restart every time). Also power draw in kernel manager shows more current draw. Basically the bug is, that kernel I'm using is not on the 'whitelist'. And because of that it won't even install, hich is a bummer 😕

**Comment by MadissonG** [comment]
I wish there would be an option to choose to continue.

**Comment by theduffster** [comment]
Can you see if you have any of the following folders in /sys/modules? If you do, then it's working as intended. 

/sys/module/high_perf_mode
/sys/module/cpe_debug_mode
/sys/module/impedance_detect_en

**Comment by MadissonG** [comment]
Just checked, and I don't have any of these.

**Comment by theduffster** [comment]
Would be highly unlikely it's working then as those are the files it uses, which makes sense, since I think your phone's processor would be too new to support this mod. You can read more about it here: https://github.com/oiakera/high_perf_dac/issues/12

**Comment by MadissonG** [comment]
Okay. Thanks very much for your help, Yesterday I was wondering for which processors does it work? Might be a good idea to list them. Switching to [https://github.com/Briclyaz/NLSound_module_QCom](url) solved everything for me.

**Comment by theduffster** [comment]
I think the key thing would be kernel support, you pretty much have to assume no stock kernels support it.
