### ISSUE TITLE
This module kills riru module.

### ISSUE THREAD

**Issue by oneironaut2209** [ahkehra/high_perf_dac#3]
After flashing this module all riru modules stoped working.
![Screenshot_20210830-123807~3](https://user-images.githubusercontent.com/63645932/131300240-750d796d-acf9-445b-a67a-dedc7c14534a.png)

post-fs-data.sh failed to run.

Tested on today's release on gauguin running Arrow os 11.

**Comment by ahkehra** [comment]
Thank you for testing the module. I try to fix this issue
