### ISSUE TITLE
Question: Is there any status?

### ISSUE THREAD

**Issue by jbrepogmailcom** [ahkehra/high_perf_dac#7]
Hello. Thanks for great piece of SW. Is there any way how I know that the module is working correctly? Any log? Thank you very much, Jan

**Comment by ahkehra** [comment]
Check your internal storage "high_perf_dac.log"

**Comment by jbrepogmailcom** [comment]
I am sorry but I do not have such file in emulated/0 folders

**Comment by jbrepogmailcom** [comment]
Sorry still did not get the response. In which folder can I find "high_perf_dac.log" please?
